trigger:
- '*'

pool:
  vmImage: 'ubuntu-22.04'
  demands:
  - npm

steps:
- task: UseDotNet@2
  displayName: 'Install .NET SDK 6.0'
  inputs:
    packageType: 'sdk'
    version: '6.x'
- task: UseDotNet@2
  displayName: 'Install .NET SDK 4.6.2'
  inputs:
    packageType: 'sdk'
    version: '4.6.2'
- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: '**/*.csproj'
    feedsToUse: 'select'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    configuration: release
    